<img src="data/omotec.png" alt="Drawing" style="width: 130px;" align="center"/>

---

# 1. Setting up Jupyter notebook
### We will be using jupyter notebook throughou the course as it is very easy to use.

We will be installing jupyter notebook inside the python installation itself. 


---

**For Windows**

 - open command prompt and type

`pip install jupyter`

---

**For Mac**

 - open Terminal and type

`pip3 install jupyter`

<img src="data/jupyter.jpg" alt="Drawing" style="width: 600px;" align="center"/>

#### Once the installation process is over open command prompt or terminal and type `jupyter notebook`
<img src="data/jupyter_1.jpg" alt="Drawing" style="width: 600px;" align="center"/>

#### This should open a new browser window which is the Jupyter notebook
**NOTE : Don't close the terminal/command prompt while you are using jupyter notebook**

## NumPy:
<p>NumPy is a Python library used for working with arrays.</p>

## Use of NumPy:
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

### The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.`

In [3]:
#Creating array : we can create numpy array using array() function 

In [4]:
import numpy as np

a=np.array([1,2,6])

print(a)

[1 2 6]


In [5]:
#checking type

In [6]:
import numpy as np

a=np.array([1,2,6])

print(a)
print(type(a))

[1 2 6]
<class 'numpy.ndarray'>


In [7]:
#creating array with tuple 

In [8]:
import numpy as np

a=np.array((1,2,6))

print(a)
print(type(a))

[1 2 6]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

a=(12,23,45)
print(type(a))

b= np.array(a)
print(type(b))


<class 'tuple'>
<class 'numpy.ndarray'>


## HOMEWORK

1. write a program to create numpy array using list

## HOMEWORK SOLUTION 

In [12]:
#TASK 1

import numpy as np

a=[12,23,45]
print(type(a))

b= np.array(a)
print(type(b))


<class 'list'>
<class 'numpy.ndarray'>
