## Homework Solutions

1) Create a 0D array

In [1]:
import numpy as np

arr = np.array(2)

print(arr)
print(arr.ndim)

2
0


2) Create a 1D array

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


3) Create a 2D array

In [3]:
import numpy as np

arr = np.array([[75, 93, 83], [22, 14, 36]])

print(arr)

[[75 93 83]
 [22 14 36]]


4) Print the last element from the 2nd dimension

In [4]:
import numpy as np

arr = np.array([[75, 93, 83], [22, 14, 36]])

print(arr[1,2])

36


5) Access the third element of the second array of the first array

In [5]:
import numpy as np

arr = np.array([[[22, 32, 43], [54, 6, 7]], [[7, 68, 49], [1, 11, 32]]])

print(arr[0, 1, 2])

7


6) Get third and fourth elements from the following array and add them.

In [6]:
import numpy as np

arr = np.array([11, 22, 33, 54])

print(arr[2] + arr[3])

87


7. Create a numpy array of shape (3, 5) with integers from 1 to 10. Slice the array to obtain the first row.

In [7]:
import numpy as np

# Create a numpy array of shape (3, 5) with integers from 1 to 10
arr = np.array([[5, 6, 5, 4, 10], [1, 6, 4, 4, 4], [3, 7, 6, 5, 1]])

# Slice the array to obtain the first row
first_row = arr[0,0:5] # you can even use indexing here : arr[0]

# Print the original array and the first row
print("Original array:\n", arr)
print("First row:\n", first_row)



Original array:
 [[ 5  6  5  4 10]
 [ 1  6  4  4  4]
 [ 3  7  6  5  1]]
First row:
 [ 5  6  5  4 10]


8. Create a numpy array of shape (5, 5) with integers from 1 to 20. Slice the array to obtain the second column, but only the first three elements.



In [8]:
import numpy as np

# Create a numpy array of shape (5, 5) with integers from 1 and 20
arr = np.array([[5, 16, 15, 4, 10], [1, 6, 14, 4, 4], [13, 7, 6, 5, 11], [1, 16, 4, 4, 14], [3, 17, 6, 5, 12]])


# Slice the array to obtain the second column, but only the first three elements
second_col = arr[:3, 1]

# Print the original array and the sliced array
print("Original array:\n", arr)
print("Second column (first three elements):\n", second_col)

Original array:
 [[ 5 16 15  4 10]
 [ 1  6 14  4  4]
 [13  7  6  5 11]
 [ 1 16  4  4 14]
 [ 3 17  6  5 12]]
Second column (first three elements):
 [16  6  7]


<hr>