# Homework Questions

1) Make a view,change the view and display both arrays
    ```
    arr = [21, 23, 34, 74, 5]
    Update the zeroth index to 65
    ```

In [2]:
import numpy as np

arr = np.array([21, 23, 34, 74, 5])
x = arr.view()
print(arr)
x[0] = 65


print(x)

[21 23 34 74  5]
[65 23 34 74  5]


2) Make a copy, change the original array, and display both arrays
    ```
    arr = [78, 27, 23, 74, 75]
    Update the zeroth index to 29
    ```

In [3]:
import numpy as np

arr = np.array([78, 27, 23, 74, 75])
x = arr.copy()
arr[0] = 29

print(arr)
print(x)

[29 27 23 74 75]
[78 27 23 74 75]


3) Write Code to perform Sorting on the below 2 D array
    ```
    arr = [[39, 20, 74], [75, 90, 81]]
    ```

In [4]:
import numpy as np

arr = np.array([[39, 20, 74], [75, 90, 81]])

print(np.sort(arr))

[[20 39 74]
 [75 81 90]]


4) Sort the below array in alphabetical order
    ```
    arr = ['figs', 'cherry', 'mango']
    ```

In [5]:
import numpy as np

arr = np.array(['figs', 'cherry', 'mango'])

print(np.sort(arr))

['cherry' 'figs' 'mango']


5) Write code for Creating Filter Directly from Array, so will return only even elements from the original array a=[22,32,54,25,33]

In [7]:
import numpy as np

arr = np.array([22, 32, 54,25,33])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[True, True, True, False, False]
[22 32 54]


6) Create a NumPy Filter Array for the below numPy Array using the below Boolean Filter pattern
```
   arr = np.array([4, 3, 40, 6]) x=[True,False,False,True]
```

In [8]:
import numpy as np

arr = np.array([4, 3, 40, 6])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[ 4 40]


7) Create code to Flatten the below 2D array to 1-D Format
```
   a=([[1,4,7], [2,5,8],[3,6,9]])
```

In [9]:
import numpy as np

arr = np.array([[1,4,7], [2,5,8],[3,6,9]])

newarr = arr.reshape(-1)

print(newarr)

[1 4 7 2 5 8 3 6 9]
