## Homework Solution

1) Checking the data type of array

In [3]:
# importing numpy library
import numpy as np

# creating and initializing an array
arr = np.array([1.2, 2.3, 3.5, 2.7, 5.6, 10.10])

# printing the array and checking datatype
print('Array:', arr)

print('Datatype:', arr.dtype)

Array: [ 1.2  2.3  3.5  2.7  5.6 10.1]
Datatype: float64


2) Create two Arrays & Stack them vertically

In [4]:
import numpy as np
  
x = np.array([1, 2, 3, 4, 5])
y = np.array([16, 17, 18, 19, 20])
print('First array:\n', x)
print('Second array:\n', y)
print('Vertically stacked array:\n', np.vstack((x, y)))


First array:
 [1 2 3 4 5]
Second array:
 [16 17 18 19 20]
Vertically stacked array:
 [[ 1  2  3  4  5]
 [16 17 18 19 20]]


3) Create two Arrays & Stack them horizontally

In [5]:
import numpy as np
  
x = np.array([1, 2, 3, 4, 5])
y = np.array([16, 17, 18, 19, 20])
print('First array:\n', x)
print('Second array:\n', y)
print('Horizontally stacked array:\n', np.hstack((x, y)))


First array:
 [1 2 3 4 5]
Second array:
 [16 17 18 19 20]
Horizontally stacked array:
 [ 1  2  3  4  5 16 17 18 19 20]


4) dtype of the given array object is ‘int32’. Now change this to ‘float64’ type.

In [6]:
# change the dtype to 'float64'
# importing the numpy library as np
import numpy as np

# Create a numpy array
arr = np.array([10, 20, 30, 40, 50])
arr = arr.astype('float64')

# Print the array
print(arr)
# Print the dtype
print(arr.dtype)

[10. 20. 30. 40. 50.]
float64


5) convert int into strings of  arr [1, 2, 3, 8, 7, 5]

In [7]:
import numpy as np

# Creating and initializing array with datatype
arr = np.array([1, 2, 3, 8, 7, 5], dtype='S')

# printing array and its datatype
print("Array:", arr)
print("Datatype:", arr.dtype)

Array: [b'1' b'2' b'3' b'8' b'7' b'5']
Datatype: |S1


6) Stack the given arrays along columns, arr1=[1, 2, 3] &  arr2=[12,13,14]

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([12, 13, 14])

arr = np.vstack((arr1, arr2))

print(arr)

[[ 1  2  3]
 [12 13 14]]


7) Stack the given arrays along Rows, arr1=[1, 2, 3] & arr2=[12,13,14]

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([12, 13, 14])

arr = np.hstack((arr1, arr2))

print(arr)

[ 1  2  3 12 13 14]


8) Join the given arrays arr1=[15,16,17] & arr2=[78,89,45]

In [12]:
import numpy as np

arr1 = np.array([15, 16, 17])

arr2 = np.array([78, 89, 45])

arr = np.concatenate((arr1, arr2))

print(arr)


[15 16 17 78 89 45]


9) Create a 1D array & then Convert it into a 2D array of shape 4x2 & 2x4

In [14]:
import numpy as np
# 1-D array having elements [1 2 3 4 5 6 7 8]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Now we can convert this 1-D array into a 2-D array of shape 4x2 & 2x4

# 1. having dimension 4 x 2
arr1 = arr.reshape(4, 2)
print ('After reshaping having dimension 4x2:')
print (arr1)
print ('\n')

# 2. having dimension 2 x 4
arr2 = arr.reshape(2, 4)
print ('After reshaping having dimension 2x4:')
print (arr2)
print ('\n')

After reshaping having dimension 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


After reshaping having dimension 2x4:
[[1 2 3 4]
 [5 6 7 8]]


